image:
  file: .gitpod.Dockerfile

  
tasks:
  - before: >
      source ~/.bashrc
    init: >
      gradle --version
      sudo chmod +x run.sh
    command: >
      ./run.sh
  


ports:
  - port: 5050
    onOpen: open-preview
